---
- name: "Create activation key SAP Clients"
  katello_activation_key:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "SAP Clients"
    lifecycle_environment: "TechLab"
    content_view: 'CCV: SAP Applications'
    subscriptions:
      - name: "{{ satellite_subscription_name }}"
    content_overrides:
        - label: rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-ha-for-rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-sap-for-rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-sap-hana-for-rhel-7-server-e4s-rpms
          override: enabled
    auto_attach: False
    release_version: "7.6"
