---
- name: "Enable Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable Red Hat Enterprise Linux High Availability Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-ha-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable RHEL for SAP for RHEL Server Update Services for SAP Solutions RPMs repository set "
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-sap-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable RHEL for SAP HANA for RHEL Server Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-sap-hana-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Create or update weekly RHEL sync plan"
  katello_sync_plan:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "Weekly SAP RHEL Sync"
    interval: "weekly"
    enabled: false
    sync_date: "2020-01-01 00:00:00 UTC"
    products:
      - 'Red Hat Enterprise Linux Server - Update Services for SAP Solutions'
      - 'Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions'
      - 'RHEL for SAP HANA - Update Services for SAP Solutions'
      - 'RHEL for SAP - Update Services for SAP Solutions'
    state: present

- name: "Create or update RHEL Server content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 7.6 Server"
    repositories:
      - name: 'Red Hat Enterprise Linux 7 Server - Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'Red Hat Enterprise Linux Server - Update Services for SAP Solutions'

- name: "Create or update RHEL HA content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 7.6 High Availability"
    repositories:
      - name: 'Red Hat Enterprise Linux High Availability for RHEL 7 Server Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions'
