---
- name: "Enable Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable Red Hat Enterprise Linux High Availability Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-ha-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable RHEL for SAP for RHEL Server Update Services for SAP Solutions RPMs repository set "
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-sap-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Enable RHEL for SAP HANA for RHEL Server Update Services for SAP Solutions RPMs repository set"
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: rhel-sap-hana-for-rhel-7-server-e4s-rpms
    repositories:
    - releasever: "7.6"
      basearch: "x86_64"
    state: enabled

- name: "Create or update weekly RHEL sync plan"
  katello_sync_plan:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "Weekly SAP RHEL Sync"
    interval: "weekly"
    enabled: false
    sync_date: "2020-01-01 00:00:00 UTC"
    products:
      - 'Red Hat Enterprise Linux Server - Update Services for SAP Solutions'
      - 'Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions'
      - 'RHEL for SAP HANA - Update Services for SAP Solutions'
      - 'RHEL for SAP - Update Services for SAP Solutions'
    state: present

- name: "Create or update RHEL Server content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL Server"
    repositories:
      - name: 'Red Hat Enterprise Linux 7 Server - Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'Red Hat Enterprise Linux Server - Update Services for SAP Solutions'

- name: "Create or update RHEL High Availability content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL High Availability"
    repositories:
      - name: 'Red Hat Enterprise Linux High Availability for RHEL 7 Server Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions'

- name: "Create or update RHEL for SAP Update Services content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP Applications"
    repositories:
      - name: 'RHEL for SAP for RHEL 7 Server Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'RHEL for SAP - Update Services for SAP Solutions'

- name: "Create or update RHEL for SAP HANA Update Services content view "
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP HANA"
    repositories:
      - name: 'RHEL for SAP HANA for RHEL 7 Server Update Services for SAP Solutions RPMs x86_64 7.6'
        product: 'RHEL for SAP HANA - Update Services for SAP Solutions'

- name: "Create a composite content view for SAP Application hosts"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CCV: SAP Applications"
    composite: true
    auto_publish: true
    components:
      - content_view: "CV: RHEL Server"
        latest: true
      - content_view: "CV: RHEL High Availability"
        latest: true
      - content_view: "CV: RHEL for SAP Applications"
        latest: true

- name: "Create a composite content view for SAP HANA hosts"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CCV: SAP HANA"
    composite: true
    auto_publish: true
    components:
      - content_view: "CV: RHEL Server"
        latest: true
      - content_view: "CV: RHEL High Availability"
        latest: true
      - content_view: "CV: RHEL for SAP HANA"
        latest: true

- name: "Add a TechLab lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "TechLab"
    label: "techlab"
    prior: "Library"
    description: "The TechLab environment"
    state: "present"

- name: "Add a Sandbox lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "Sandbox"
    label: "Sandbox"
    prior: "TechLab"
    description: "The Sandbox environment"
    state: "present"

- name: "Add a DEV lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "DEV"
    label: "dev"
    prior: "Sandbox"
    description: "The DEV environment"
    state: "present"

- name: "Add a UAT lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "UAT"
    label: "uat"
    prior: "DEV"
    description: "The UAT environment"
    state: "present"

- name: "Add a PROD lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "PROD"
    label: "prod"
    prior: "UAT"
    description: "The PROD environment"
    state: "present"
