---
- name: Create ansible-satellite tower project
  tower_project:
    name: "Satellite Automation"
    description: "Create necessary SAP content for Red Hat Satellite"
    organization: "Zurich Insurance"
    scm_url: "https://github.com/rhatservices/ansible-satellite.git"
    scm_type: "git"
    scm_update_on_launch: "yes"
    scm_update_cache_timeout: 60
    # scm_credential: "{{ item.1.scm_credential | default(omit) }}"
    # scm_branch: "{{ item.1.scm_branch | default('master') }}"
    state: "present"
    custom_virtualenv: "omit"
