- name: Deploy OS Patches and reboot maschine
  hosts: DEV
  tasks:
    - name: upgrade all packages with yum
      yum:
        name: '*'
        state: latest
      register: os_upgrade_done

    - name: reboot node after upgrade
      reboot:
      # disabled for the demo
      # when: os_upgrade_done.changed
