- name: promote CCV {{ satellite_ccv}} to {{ sap_satellite_update_dest_environment }}
  hosts: localhost
  become: false
  roles:
    - role: sap_satellite_update
      vars:
        sap_satellite_update_promote: true
