---
- name: "Publish a content view and promote that version to DEV"
  theforeman.foreman.katello_content_view_version:
    username: "{{ ansible_satellite_username }}"
    password: "{{ ansible_satellite_password }}"
    server_url: "https://satellite.tower.local"
    content_view: "DEV"
    organization: "lab"
    lifecycle_environments:
      - Library
      - DEV
  when: ansible_satellite_promote_dev|bool


- name: "Promote current DEV version to PROD"
  theforeman.foreman.katello_content_view_version:
    username: "{{ ansible_satellite_username}}"
    password: "{{ ansible_satellite_password }}"
    server_url: "https://satellite.tower.local"
    verify_ssl: False
    content_view: "DEV"
    organization: "lab"
    current_lifecycle_environment: DEV
    lifecycle_environments:
      - PROD
  when: ansible_satellite_promote_prod|bool
