---
- name: "Create activation key SAP Application clients"
  katello_activation_key:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ sap_satellite_configure_sat_organization }}"
    name: "SAP Applications"
    lifecycle_environment: "TechLab"
    content_view: 'CCV: SAP Applications'
    subscriptions:
      - name: "{{ sap_satellite_configure_sat_subscription_name }}"
    content_overrides:
        - label: rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-ha-for-rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-sap-for-rhel-7-server-e4s-rpms
          override: enabled
    auto_attach: False
    release_version: "7.6"


- name: "Create activation key SAP HANA clients"
  katello_activation_key:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ sap_satellite_configure_sat_organization }}"
    name: "SAP HANA"
    lifecycle_environment: "TechLab"
    content_view: 'CCV: SAP HANA'
    subscriptions:
      - name: "{{ sap_satellite_configure_sat_subscription_name }}"
    content_overrides:
        - label: rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-ha-for-rhel-7-server-e4s-rpms
          override: enabled
        - label: rhel-sap-hana-for-rhel-7-server-e4s-rpms
          override: enabled
    auto_attach: False
    release_version: "7.6"
