- name: "Create or update RHEL Server content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP Server"
    repositories:
      - name: 'Red Hat Enterprise Linux 7 Server - Update Services for SAP Solutions RPMs {{ sap_satellite_configure_architecture }} {{ sap_satellite_configure_rhel_release }}'
        product: 'Red Hat Enterprise Linux Server - Update Services for SAP Solutions'
  register: cv_rhelserver

- name: "Publish an initial version of the RHEL Server content view"
  katello_content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    content_view: "CV: RHEL for SAP Server"
    lifecycle_environments:
      - Library
  when: cv_rhelserver.changed

- name: "Create or update RHEL High Availability content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP High Availability"
    repositories:
      - name: 'Red Hat Enterprise Linux High Availability for RHEL 7 Server Update Services for SAP Solutions RPMs {{ sap_satellite_configure_architecture }} {{ sap_satellite_configure_rhel_release }}'
        product: 'Red Hat Enterprise Linux High Availability - Update Services for SAP Solutions'
  register: cv_rhelha

- name: "Publish an initial version of the RHEL High Availability content view"
  katello_content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    content_view: "CV: RHEL for SAP High Availability"
    lifecycle_environments:
      - Library
  when: cv_rhelha.changed

- name: "Create or update RHEL for SAP Update Services content view"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP Applications"
    repositories:
      - name: 'RHEL for SAP for RHEL 7 Server Update Services for SAP Solutions RPMs {{ sap_satellite_configure_architecture }} {{ sap_satellite_configure_rhel_release }}'
        product: 'RHEL for SAP - Update Services for SAP Solutions'
  register: cv_rhelsapapp

- name: "Publish an initial version of the RHEL for SAP Applications content view"
  katello_content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    content_view: "CV: RHEL for SAP Applications"
    lifecycle_environments:
      - Library
  when: cv_rhelsapapp.changed

- name: "Create or update RHEL for SAP HANA Update Services content view "
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL for SAP HANA"
    repositories:
      - name: 'RHEL for SAP HANA for RHEL 7 Server Update Services for SAP Solutions RPMs {{ sap_satellite_configure_architecture }} {{ sap_satellite_configure_rhel_release }}'
        product: 'RHEL for SAP HANA - Update Services for SAP Solutions'
  register: cv_rhelsaphana

- name: "Publish an initial version of the RHEL for SAP HANA content view"
  katello_content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    content_view: "CV: RHEL for SAP HANA"
    lifecycle_environments:
      - Library
  when: cv_rhelsaphana.changed

- name: "Create a composite content view {{ satellite_ccv_name }}"
  katello_content_view:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_ccv_name }}"
    composite: true
    auto_publish: false
    components:
      - content_view: "CV: RHEL for SAP Server"
        latest: true
      - content_view: "CV: RHEL for SAP High Availability"
        latest: true
      - content_view: "CV: RHEL for SAP Applications"
        latest: true
      - content_view: "CV: RHEL for SAP HANA"
        latest: true
  register: ccv_sapapp

- name: "Publish an initial version of the {{satellite_ccv_name }} composite content view"
  katello_content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    content_view: "{{ satellite_ccv_name }}"
    lifecycle_environments:
      - Library
      - TechLab
  when: ccv_sapapp.changed
