---
- name: "Add lifecycle environments"
  katello_lifecycle_environment:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "{{ item.name }}"
    label: "{{ item.name | lower }}"
    prior: "{{ item.prior }}"
    description: "The {{ item.name }} environment"
    state: "present"
  when: lifecycle_environments is defined
  loop: "{{ lifecycle_environments }}"
